### ISSUE TITLE
能否将抓取的评论数据存到一个 xlsx表之类的呢？

### ISSUE THREAD

**Issue by Durancer** [jiansenc/tiktok_barrage_nodejs#4]

**Comment by jxyk2007** [comment]
可以
`import websocket
import json
import requests
import pandas as pd
def savefile(name ，msg_content):
  # 创建数据
  data = {'name': name],
          'age': msg_content}

  # 创建DataFrame对象
  df = pd.DataFrame(data)
  # 保存到Excel表格中
  df.to_excel('data.xlsx', index=False)

def on_message(ws, message):
    print(f"Received: {message}")
    print('---------------------------------------------------------------------')
    message = json.loads(message)##字符串转为字典
    print(type(message))
    print(message['message']['user_nickName'])
    print(message['message']['msg_content'])
    print('***************************************************************************')
    savefile(message['message']['user_nickName'] ，message['message']['msg_content']))
        

def on_error(ws, error):
    print(f"Error: {error}")

def on_close(ws):
    print("Connection closed")

def on_open(ws):
    print("Connection opened")

if __name__ == "__main__":
    ws_url = "ws://127.0.0.1:9527/"
    ws = websocket.WebSocketApp(ws_url,
                                on_message=on_message,
                                on_error=on_error,
                                on_close=on_close)
    ws.on_open = on_open
    ws.run_forever()
`
