### ISSUE TITLE
之前能抓到，现在不好用了

### ISSUE THREAD

**Issue by knight965** [jiansenc/tiktok_barrage_nodejs#9]
客户端正常连接，窗口也打开了，但就是抓不到弹幕。

> dy@1.0.0 dev
> node ./app.js

打开-> http://127.0.0.1:9527
客户端连接成功

**Comment by knight965** [comment]
index.js?t=0.9505528847926172:120 Uncaught TypeError: Cannot read properties of undefined (reading 'urlList')
    at Barrage.getUser (index.js?t=0.9505528847926172:120:43)
    at Barrage.messageParse (index.js?t=0.9505528847926172:156:45)
    at MutationObserver.<anonymous> (index.js?t=0.9505528847926172:95:44)

**Comment by netstat1grep80** [comment]
按着

> index.js?t=0.9505528847926172:120 Uncaught TypeError: Cannot read properties of undefined (reading 'urlList') at Barrage.getUser (index.js?t=0.9505528847926172:120:43) at Barrage.messageParse (index.js?t=0.9505528847926172:156:45) at MutationObserver. (index.js?t=0.9505528847926172:95:44)

抖音返回的数据个别字段命名发生了变化，根据控制台的错误信息，去手工改一下程序，client.js和index.js本地部署，控制台注入时候，将https://jiansenc.github.io/xxxxxxx/client.js改成你本地地址就可以了，client.js里的引用index.js的地方也要改

**Comment by Shelby50-h** [comment]
怎么解决呀

**Comment by siwuai** [comment]
@Shelby50-h 
avatarThumb.urlList 改成 avatar_thumb.url_list
repeatCount 改成 repeat_count
diamondCount 改成 diamond_count
icon.urlListList 改成 icon.url_list
user_isAdmin: user.userAttr.isAdmin  直接删掉

**Comment by qq357075581** [comment]
> 按着
> 
> > index.js?t=0.9505528847926172:120 Uncaught TypeError: Cannot read properties of undefined (reading 'urlList') at Barrage.getUser (index.js?t=0.9505528847926172:120:43) at Barrage.messageParse (index.js?t=0.9505528847926172:156:45) at MutationObserver. (index.js?t=0.9505528847926172:95:44)
> 
> 抖音返回的数据个别字段命名发生了变化，根据控制台的错误信息，去手工改一下程序，client.js和index.js本地部署，控制台注入时候，将[https://jiansenc.github.io/xxxxxxx/client.js改成你本地地址就可以了，client.js里的引用index.js的地方也要改](https://jiansenc.github.io/xxxxxxx/client.js%E6%94%B9%E6%88%90%E4%BD%A0%E6%9C%AC%E5%9C%B0%E5%9C%B0%E5%9D%80%E5%B0%B1%E5%8F%AF%E4%BB%A5%E4%BA%86%EF%BC%8Cclient.js%E9%87%8C%E7%9A%84%E5%BC%95%E7%94%A8index.js%E7%9A%84%E5%9C%B0%E6%96%B9%E4%B9%9F%E8%A6%81%E6%94%B9)

你好，请问要改的这个地址是项目在硬盘上的路径吗？
